version: "3"
services:
  app:
    build: ./infra/php
    volumes: 
      - ./html:/var/www/html
    depends_on: 
      - db
  web:
    image: nginx
    ports: 
      - 8888:80
    volumes: 
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    depends_on: 
      - app
  db:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
volumes:
  db_data: