version: "3"
services:
  app:
    build: ./infra/php
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes: 
      - ./html:/var/www/html
    depends_on: 
      - db
    working_dir: /var/www/html/breeze-sample
  web:
    image: nginx
    ports: 
      - 8888:80
    volumes: 
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    depends_on: 
      - app
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: laravel_breeze_db
      MYSQL_USER: laravel_breeze_user
      MYSQL_PASSWORD: laravel_breeze_password
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - 3306:3306
    volumes: 
      - db_data:/var/lib/mysql
volumes:
  db_data: